[package]
name = "self-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
chrono = "0.4.22"
dryoc = "0.4.2"
hex = "0.4.3"
ntp = "0.5.0"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1.0.87"
uuid = "1.2.1"

[dev-dependencies]
httptest = "0.15.4"