[package]
name = "self-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
chrono = "0.4.22"
dryoc = "0.4.2"
ntp = "0.5.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1.0.87"
uuid = "1.2.1"
